spring:
  datasource:
    url: jdbc:mysql://localhost:3306/test
    driver-class-name: com.mysql.jdbc.Driver
    username: root
    password: mysql@123456
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
